//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Body {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Body() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Body", typeof(Body).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Մեր մասին.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Լավագույն առաջարկները.
        /// </summary>
        public static string BestOffers {
            get {
                return ResourceManager.GetString("BestOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Բլոգ.
        /// </summary>
        public static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Տեսեք մեր լավագույն տուրերը.
        /// </summary>
        public static string CheckTopTours {
            get {
                return ResourceManager.GetString("CheckTopTours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Հյուրերի քանակը.
        /// </summary>
        public static string CountOfTourist {
            get {
                return ResourceManager.GetString("CountOfTourist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to կարող է լինել 1-մինչև 1000.
        /// </summary>
        public static string CountOfTouristRange {
            get {
                return ResourceManager.GetString("CountOfTouristRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Էլ․ հասցե.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ներողություն, գործողությունը չհաջողվեց.
        /// </summary>
        public static string FailedSubscriptionMessage {
            get {
                return ResourceManager.GetString("FailedSubscriptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - ֆիլտրել ըստ տեսակի -.
        /// </summary>
        public static string FilterByCategory {
            get {
                return ResourceManager.GetString("FilterByCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - ֆիլտրել ըստ երկրի -.
        /// </summary>
        public static string FilterByCountry {
            get {
                return ResourceManager.GetString("FilterByCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ԳՏՆԵԼ ԿԱՏԱՐՅԱԼ ՏՈՒՐ.
        /// </summary>
        public static string FindPerfectTour {
            get {
                return ResourceManager.GetString("FindPerfectTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ձեր Անունը.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to մուտքագրեք անուն (3-ից մինչև 100 տառ).
        /// </summary>
        public static string FullNameLength {
            get {
                return ResourceManager.GetString("FullNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Առաջինը իմացիր լավագույն առաջարկների մասին.
        /// </summary>
        public static string GetBestOffers {
            get {
                return ResourceManager.GetString("GetBestOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Վստահեք Ձեր հաջորդ հանգիստը մեզ.
        /// </summary>
        public static string LetsBook {
            get {
                return ResourceManager.GetString("LetsBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Հաղորդագրություն.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Չհաջողվեց ուղարկել հաղորդագրությունը.
        /// </summary>
        public static string MessageFailed {
            get {
                return ResourceManager.GetString("MessageFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to մուտքագրեք հաղորդագրություն (0-ից մինչև 1000 տառ).
        /// </summary>
        public static string MessageLength {
            get {
                return ResourceManager.GetString("MessageLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Հաղորդագրությունը հաջողությամբ ուղարկվեց.
        /// </summary>
        public static string MessageSent {
            get {
                return ResourceManager.GetString("MessageSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to առնվազն 10 տառ.
        /// </summary>
        public static string Min10 {
            get {
                return ResourceManager.GetString("Min10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to առնվազն 3 տառ.
        /// </summary>
        public static string Min3 {
            get {
                return ResourceManager.GetString("Min3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to մուտքագրեք ամսաթիվ (ամիս/օր/տարի).
        /// </summary>
        public static string MustBeDate {
            get {
                return ResourceManager.GetString("MustBeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to մուտքագրեք էլ․ հասցե.
        /// </summary>
        public static string MustBeEmail {
            get {
                return ResourceManager.GetString("MustBeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to գիշեր.
        /// </summary>
        public static string Night {
            get {
                return ResourceManager.GetString("Night", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to գիշեր.
        /// </summary>
        public static string Nights {
            get {
                return ResourceManager.GetString("Nights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to գիշեր.
        /// </summary>
        public static string Nights2 {
            get {
                return ResourceManager.GetString("Nights2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Տվյալ հարցմանը համապատասխան ոչինչ չի գտնվել։.
        /// </summary>
        public static string NoTourFound {
            get {
                return ResourceManager.GetString("NoTourFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Հեռախոս.
        /// </summary>
        public static string OtherContacts {
            get {
                return ResourceManager.GetString("OtherContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Մեր պրոֆեսիոնալիզմը կօգնի Ձեզ.
        /// </summary>
        public static string Perfection1 {
            get {
                return ResourceManager.GetString("Perfection1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to գտնել Ձեր կատարյալ ճամփորդությունը.
        /// </summary>
        public static string Perfection2 {
            get {
                return ResourceManager.GetString("Perfection2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ՁԵԶ ԿԱՐՈՂ Է ՀԵՏԱՔՐՔՐԵԼ ՆԱԵՎ.
        /// </summary>
        public static string RelatedTours {
            get {
                return ResourceManager.GetString("RelatedTours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Հարցումը ուղարկված է։ Շնորհակալություն.
        /// </summary>
        public static string RequestSent {
            get {
                return ResourceManager.GetString("RequestSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Պատվիրել Տուր.
        /// </summary>
        public static string RequestTour {
            get {
                return ResourceManager.GetString("RequestTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to պարտադիր է.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ուղարկել.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ՈՒՂԱՐԿԵԼ.
        /// </summary>
        public static string SendMessage {
            get {
                return ResourceManager.GetString("SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Բաժանորդագրվել.
        /// </summary>
        public static string SubScribe {
            get {
                return ResourceManager.GetString("SubScribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Շնորհակալություն մեր նորություններին բաժանորդագրվելու համար.
        /// </summary>
        public static string SubscriptionMessage {
            get {
                return ResourceManager.GetString("SubscriptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Վերնագիր.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to մուտքագրեք վերնագիր (3-ից մինչև 100 տառ).
        /// </summary>
        public static string TitleLength {
            get {
                return ResourceManager.GetString("TitleLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Այցելության սկիզբ (ամիս/օր/տարի).
        /// </summary>
        public static string TourDate {
            get {
                return ResourceManager.GetString("TourDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Տուրեր.
        /// </summary>
        public static string Tours {
            get {
                return ResourceManager.GetString("Tours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ԲՈԼՈՐԸ․․․.
        /// </summary>
        public static string ViewAllTours {
            get {
                return ResourceManager.GetString("ViewAllTours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ինչով ենք մենք յուրահատուկ.
        /// </summary>
        public static string WeAreDifferent {
            get {
                return ResourceManager.GetString("WeAreDifferent", resourceCulture);
            }
        }
    }
}
