//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Մեր Մասին.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Երևան, Հայաստան, Հերացի 18, 0025.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Տռավլ Էջնսի.
        /// </summary>
        public static string AgencyName {
            get {
                return ResourceManager.GetString("AgencyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Կոնտակտ.
        /// </summary>
        public static string ContactPage {
            get {
                return ResourceManager.GetString("ContactPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Էլ․ փոստ.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ներողություն, գործողությունը չհաջողվեց.
        /// </summary>
        public static string FailedSubscriptionMessage {
            get {
                return ResourceManager.GetString("FailedSubscriptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Տեսնել ավելին ․․․.
        /// </summary>
        public static string FindMoreVideos {
            get {
                return ResourceManager.GetString("FindMoreVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Գտեք մեզ.
        /// </summary>
        public static string FindUsOn {
            get {
                return ResourceManager.GetString("FindUsOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Առաջինը իմացիր լավագույն առաջարկների մասին.
        /// </summary>
        public static string GetBestOffers {
            get {
                return ResourceManager.GetString("GetBestOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Վստահեք Ձեր հաջորդ հանգիստը մեզ.
        /// </summary>
        public static string LetsBook {
            get {
                return ResourceManager.GetString("LetsBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Հաղորդագրություն.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Չհաջողվեց ուղարկել հաղորդագրությունը.
        /// </summary>
        public static string MessageFailed {
            get {
                return ResourceManager.GetString("MessageFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Հաղորդագրությունը հաջողությամբ ուղարկվեց.
        /// </summary>
        public static string MessageSent {
            get {
                return ResourceManager.GetString("MessageSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Անուն.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ՈՒՂԱՐԿԵԼ.
        /// </summary>
        public static string SendMessage {
            get {
                return ResourceManager.GetString("SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Բաժանորդագրվել.
        /// </summary>
        public static string SubScribe {
            get {
                return ResourceManager.GetString("SubScribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Շնորհակալություն մեր նորություններին բաժանորդագրվելու համար.
        /// </summary>
        public static string SubscriptionMessage {
            get {
                return ResourceManager.GetString("SubscriptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Տեսադարան.
        /// </summary>
        public static string VideoGallery {
            get {
                return ResourceManager.GetString("VideoGallery", resourceCulture);
            }
        }
    }
}
