// <auto-generated />
namespace Travel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class tours_forKey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tours_forKey));
        
        string IMigrationMetadata.Id
        {
            get { return "201801312112073_tours_forKey"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
