// <auto-generated />
namespace Travel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class country_tagline : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(country_tagline));
        
        string IMigrationMetadata.Id
        {
            get { return "201803110034301_country_tagline"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
